config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :articles
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_action :set_categories

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :description, :category_id )
  end

  def set_categories
    @categories = Category.all
  end

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to articles_path
    else
      render :new
    end
  end

  private

    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_with model: @article, data: { turbo: false }  do |form| %> 
  <% if @article.errors.any? %>
   <% @article.errors.full_messages.each do |message| %>
     <p><%= message %></p>
   <% end %>
  <% end %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "60x10" %>
  </div>


	<%= form.submit %>
<% end %>

app/views/articles/index.html.erb
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Delete', article, data: {turbo_method: :delete} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Create New Article', new_article_path %>

<% @categories.each do |category| %>
  <%= category.category %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "60x10" %>
  </div>

  <%= form.select :category_id, Category.all.map{ |c| [c.category, c.id] },:include_blank => "Select One" %>

  <%= form.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h4 class="card-title"><%= @article.title %></h4>
    <h6 class="card-title"><%= @article.category.category %></h6>
    <p class="card-text"><%= @article.description %></p>
    <%= link_to 'Edit', edit_article_path(@article), class:"card-link"%>
    <%= link_to 'Delete', @article, data: {turbo_method: :delete}, class:"card-link" %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </div>
  <%= form.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container mt-4">
        <%= yield %>
      </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#">
      <%= link_to 'Home', root_path, class: "navbar-brand" %> 
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Category', new_category_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>